# Generated by Django 4.1 on 2023-04-18 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_register_dtm",
            new_name="user_register_dttm",
        ),
    ]
