# Generated by Django 4.1 on 2023-04-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_rename_user_register_dtm_user_user_register_dttm"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "유저관리", "verbose_name_plural": "유저관리"},
        ),
        migrations.AlterModelTable(
            name="user",
            table="sign_up",
        ),
    ]
