# Generated by Django 4.1.4 on 2023-06-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_options_alter_user_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_pw_confirm",
            field=models.CharField(max_length=130, null=True, verbose_name="비밀번호 확인"),
        ),
    ]
