# Generated by Django 4.1.4 on 2023-05-29 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_options_alter_user_table"),
        ("board", "0003_board_is_temporary_board_temporary_saved_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="is_temporary",
        ),
        migrations.RemoveField(
            model_name="board",
            name="temporary_saved_at",
        ),
        migrations.CreateModel(
            name="TemporaryBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="글 제목")),
                ("contents", models.TextField(verbose_name="글 내용")),
                (
                    "temporary_saved_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="임시저장 시간"),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "임시저장 게시판",
                "verbose_name_plural": "임시저장 게시판",
                "db_table": "temporary_board",
            },
        ),
    ]
